### ISSUE TITLE
https://reflex-frp.org is broken

### ISSUE THREAD

**Issue by benkolera** [reflex-frp/reflex-frp.org#15]
Looks like we need to twiddle some settings with the new https gh pages. :)

![reflex-frp org](https://user-images.githubusercontent.com/159197/40531621-35e78d48-6040-11e8-9ab3-c48ccdca2f53.png)

**Comment by ryantrinkle** [comment]
Yes, for some reason GitHub pages isn't allowing me to check the "enable
https" box. Says a certificate "has not yet been issued", iirc. Has been
saying that for a few days.

**Comment by ghuntley** [comment]
Related https://github.com/reflex-frp/reflex-frp/issues/6

**Comment by ryantrinkle** [comment]
@benkolera @ghuntley Thanks for reporting, and this is now fixed!  This will become default in obelisk soon.
