### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by ryantrinkle** [reflex-frp/reflex-frp.org#16]
The header links as currently deployed are broken

**Comment by imalsogreg** [comment]
And, hitting the `back` button after following a broken link results in `No handler accepted "/documentation"`

e.g., 
```
reflex-frp.org  ->
click Documentation ->
click Reflex Basic Documentation  ( read the docs 404 ) ->
click Back button ( snap 404 )
```

It seems the route itself isn't be handled by snap - just going directly to `https://reflex-frp.org/documentation` fails.

**Comment by ryantrinkle** [comment]
Working on this in the `routes` branch :)

**Comment by ryantrinkle** [comment]
@imalsogreg Fixed :)
