### ISSUE TITLE
Weird broken link back button behavior

### ISSUE THREAD

**Issue by mightybyte** [reflex-frp/reflex-frp.org#22]
Steps to reproduce:

1. Go to http://reflex-frp.org/
2. Click "Tutorials"
3. Click "reflex-dom-inbits"
4. Click your browser's back button

Actual results:

```
No handler accepted "/tutorials"
```

Expected results: I should see the tutorials page again.

**Comment by ryantrinkle** [comment]
Already captured in https://github.com/reflex-frp/reflex-frp.org/issues/21 :)
