### ISSUE TITLE
Add HExplore to full-stack app list

### ISSUE THREAD

**Issue by gspia** [reflex-frp/reflex-frp.org#27]
Is there still room for apps: 

http://hexplore.mightybyte.net/
https://gitlab.com/mightybyte/hexplore/

**Comment by philderbeast** [comment]
This example is included in the list of examples up at https://reflex-frp.org/examples. Can this issue be closed?

**Comment by dfordivam** [comment]
@philderbeast indeed! I added it a little while back..
