### ISSUE TITLE
Documentation contains a few broken links

### ISSUE THREAD

**Issue by AnthonySuper** [reflex-frp/reflex-frp.org#33]
The reflex-frp.org website contains a few broken links.

More specifically..

- The [Server-Side Rendering](http://docs.reflex-frp.org/en/latest/reflex_dom_docs.html#static-server-side-rendering) refers to an [example that 404s](https://github.com/reflex-frp/reflex-frp.org/blob/master/code-snippets/StaticBuilder.hs)
- The [DOM Input Elements Section](http://docs.reflex-frp.org/en/latest/reflex_dom_docs.html#dom-input-elements) refers to an `input_widgets.hs`, which [also 404s](https://github.com/reflex-frp/reflex-frp.org/blob/master/code-snippets/input_widgets.hs)

**Comment by dfordivam** [comment]
Fixed. 
Till we take care of #14 I did a temporary fix.
