### ISSUE TITLE
Haddock+Hoogle for Reflex

### ISSUE THREAD

**Issue by dfordivam** [reflex-frp/reflex-frp.org#9]
I think it would be good to have haddock hosted on github and may be updated nightly, so that we have an easy access to the latest haddock.

I intend to link haddock to the docs, so need a proper place to have the latest version.

**Comment by mightybyte** [comment]
Fantastic idea!

**Comment by ryantrinkle** [comment]
Agreed.

**Comment by 3noch** [comment]
Up-to-date haddocks *anywhere* is a great idea. :P

**Comment by 3noch** [comment]
That's my way of saying 👍

**Comment by ryantrinkle** [comment]
@3noch They're in the try-reflex shell :D But on the internet would also be awesome.

**Comment by dfordivam** [comment]
@ryantrinkle can this be generated along with the nix cache ... ?
Like just automatic pushing of the generated html in a sub-directory of this repo...

**Comment by ElvishJerricco** [comment]
Haddocks are generated in the Nix builds. I know you can use `ghcWitihHoogle` to access them. And incidentally, both `./try-reflex` and `shell.nix` use that.

```bash
$ cd reflex-platform
$ nix-shell --run "hoogle serve --local -p 8080"
```

Having a site on reflex-frp.org that just shows this hoogle server would probably be an easy and useful way to provide docs.

**Comment by dfordivam** [comment]
Yeah good idea! 
But I am not sure whether it can work or not by simply starting a hoogle server instance... The local hoogle server points to the generated haddock html in /nix/...
For an external server it needs to be on some "static" directory...
or may be there is some way I am not aware of...

**Comment by ElvishJerricco** [comment]
The `--local` argument doesn't serve `file://` links so it should work fine, but the recommended way is probably the `--cdn` argument.

**Comment by ryantrinkle** [comment]
Yes, it'd be great to have current haddocks hosted. I always run ./cache
before pushing to develop, so if someone can figure out what needs to be
added there, we can make it a policy.

**Comment by dfordivam** [comment]
Though the "--local" argument to hoogle will be able to serve the files directly from /nix/store path...

I think the better way will be to copy the html files to a separate server (which might not even have the nix) and serve the files directly from some static dir.
I tried to implement this using the script in #11 and it seems to work fine.

**Comment by ElvishJerricco** [comment]
Isn't that what the `--cdn` argument would solve?

**Comment by dfordivam** [comment]
Yeah but --cdn argument will require the haddocs to be hosted somewhere. So we do need to host the haddocks separately...

**Comment by ElvishJerricco** [comment]
Oh I see. Using `--cdn` still requires `--local` to properly serve the haddocks. That's quite a silly deficiency on Hoogle's part.

**Comment by ElvishJerricco** [comment]
Though I just did a test and it seems Hoogle gives a 404 for any attempt to fetch arbitrary non-haddock files from the nix store.

Not to mention, if the server this runs on is already a binary cache, then it's already arbitrarily serving those files anyway.

**Comment by dfordivam** [comment]
Though it is possible to do it..

I think it would be better to get reflex on Hackage and use it from there. If we put links to an alternate haddock in the documentation, we will create one more dependency to manage.

So I will close this ..

ref: https://github.com/reflex-frp/reflex/issues/75

**Comment by srid** [comment]
See also: https://github.com/reflex-frp/reflex-platform/pull/234#issuecomment-364219252

**Comment by lspitzner** [comment]
Not aware of this issue, I recently created a simple script to host up-to-date API docs on [my server](http://hexagoxel.de/haddock/). I agree that docs around reflex are too spread out, so I will post the script to enable hosting the same in some better location.

- This is based on very basic tools only - `cabal` and `haddock`. No `nix` and no `hoogle`. Not sure if there'd be any advantage to using those instead. To fix the absolute links in the generated html I resorted to `sed`. The resulting docs should be __fully relocatable as all links are relative__.
- One thing this script does not do yet is properly mention commit hashes in the index.html. Trivial to fix.
- It does not link to hackage docs for packages that are available, but instead simply hosts all deps.
- The static size of the docs is ~700MB, compressed ~30MB. I did not purge the non-html stuff (i think there are still the haddock databases in there) but the html is the large majority anyway.

Behold my bash skills! (hah, do you even know what `${BOOTLIBLOC//\//\\\/}` does? yeah those sed lines are meant to be written once and not to be maintained.)

~~~~.sh
#!/bin/bash

set -ex

############################
# system-dependent variables
# adapt as necessary
############################

GHCSHARELOC="REPLACEME" # /usr/share/ghc or whatever that is on your system
BOOTLIBLOC="$GHCSHARELOC/doc/ghc-8.0.2/html/libraries"
COMPILERVERSIONPART="x86_64-linux-ghc-8.0.2"

####


OUTPUTDIR=$(pwd)
TEMPDIR=$(mktemp -d -t haddock-gen-XXXX)
echo "using dir $TEMPDIR"
trap 'rm -r $TEMPDIR' EXIT

TEMPDIRDOCS="$TEMPDIR/doc"
mkdir "$TEMPDIRDOCS" || true

cd "$TEMPDIR"

# build stuff, generate docs
####

git clone git@github.com:reflex-frp/reflex.git  || true
git clone git@github.com:reflex-frp/reflex-dom.git  || true
git clone git@github.com:bennofs/reflex-host.git  || true

cabal sandbox init
cabal install --enable-documentation --haddock-options='--hyperlinked-source'\
  reflex/reflex.cabal\
  reflex-dom/reflex-dom-core/reflex-dom-core.cabal\
  reflex-dom/reflex-dom/reflex-dom.cabal\
  reflex-host/reflex-host.cabal\

# copy bootlib and newly generated docs into one directory; fix absolute html
# references
####

cp -r -t "$TEMPDIRDOCS" -- "$BOOTLIBLOC"/*
cp -r -t "$TEMPDIRDOCS" -- "$TEMPDIR/.cabal-sandbox/share/doc/$COMPILERVERSIONPART/"/*

find "$TEMPDIRDOCS" -name "*.html" | xargs sed -i -e "s/file:\/\/${BOOTLIBLOC//\//\\\/}/..\/../g;s/file:\/\/${TEMPDIR//\//\\\/}\/.cabal-sandbox\/share\/doc\/$COMPILERVERSIONPART/..\/../g"

# also copy over our custom index.html
####

cp "$OUTPUTDIR/index.html" "$TEMPDIRDOCS"

# pack it up (switch to directory to have flat locations in the tar)
####

cd "$TEMPDIRDOCS"
tar -c -v -J -f "$OUTPUTDIR/doc.tar.xz" -- *

# todo: upload tar to server etc.
####
~~~~
